# Generated by Django 3.1.3 on 2020-11-24 21:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materijal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=300)),
                ('sifra', models.CharField(max_length=50)),
                ('mjerna_jedinica', models.CharField(max_length=10)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'Materijal',
            },
        ),
        migrations.CreateModel(
            name='Racuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=150)),
                ('broj_racuna', models.CharField(max_length=50)),
                ('datum', models.DateField()),
            ],
            options={
                'db_table': 'Racuni',
            },
        ),
        migrations.CreateModel(
            name='Krm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('materijalID', models.ForeignKey(db_column='materijalID', on_delete=django.db.models.deletion.CASCADE, to='racuni.materijal')),
                ('racunID', models.ForeignKey(db_column='racunID', on_delete=django.db.models.deletion.CASCADE, to='racuni.racuni')),
            ],
            options={
                'db_table': 'Krm',
            },
        ),
    ]
